### ISSUE TITLE
Small memory leak

### ISSUE THREAD

**Issue by mattfelsen** [heisters/libglvideo#6] opened 2019-06-06 22:27 UTC
Another thing we've been seeing while stress testing our apps overnight (with randomly generated touch input) is a small but steady memory leak, apparently coming from `Movie::bufferNextGPUSample()` and apparently something small and variable, ie 40, 48, or 1712 bytes, and definitely not the frame size (i.e. ~2MB for HD). To give an idea of the scale, the app launches with under 1GB of mem usage and after running overnight it's over 10GB.

I looked around in `Movie`, `Frame`, and `FrameTexture` and didn't see anything obvious, but if you've got any leads or pointers I'm sure that'd be helpful. Thanks again!

**Comment by heisters** [comment] 2019-06-07 17:19
Awesome! Thanks for finding a memory leak!

It makes sense that it would happen in `bufferNextGPUSample()`... Take a look at the method `bufferNextGPUSample()` calls: [/src/Frame.cpp#L24](/src/Frame.cpp#L24). I think that and the decoders are the only places manual memory management is happening. So also take a look at the Hap decoder: [/src/decoders/hap.cpp](/src/decoders/hap.cpp). It could be some error in the calculated texture size or something? I've never been pleased with how hap.cpp basically guesses at the texture size, and then tries making the buffer larger until it doesn't get an error [/src/decoders/hap.cpp#L100](/src/decoders/hap.cpp#L100).

**Comment by heisters** [comment] 2019-06-07 17:21
Does the memory leak repro on any of the sample apps? Or can you write a small sample app that reproduces it?

**Comment by mattfelsen** [comment] 2019-06-11 16:19
Ooh, good question. I'll run the sample apps and take a look into the decoder as well and report back 👍

**Comment by mattfelsen** [comment] 2019-06-13 15:35
I took a look with the stress sample app and am seeing what seems to be the same leak. I'll poke around a bit more, and perhaps give a shot at updating the `hap` lib/submodule to the latest, and share any updates

**Comment by heisters** [comment] 2019-06-13 19:35
ok, great. I'll try to take a look at it myself too.

**Comment by mattfelsen** [comment] 2019-06-13 21:42
Hm, no luck upgrading hap to `master` (since there are no releases) nor Bento4 to `v1.5.1-628` (the latest release). 

Re: memory management, in `Decoder::Hap`, `m_decompressedTextureBuffer` seems to be the only data buffer, and it's reused for each new frame of the movie. Doesn't seem to be the source of any leaks since it's only instantiated once per movie. Related, I never actually see that "buffer too small" warning get hit.

In `Frame`, the `m_texData` buffer is wrapped in a `unique_ptr<unsigned char[]>`, so it should get cleaned up when the frame is destructed. I also tried replacing it with a `vector<unsigned char>` (and replacing calls to `.get()` with `.data()`), but no dice either.

I don't actually see any memory allocations in `Frame::bufferTexture()` like you mention, just a copy into the pbo. 

🤔

**Comment by mattfelsen** [comment] 2019-06-25 19:04
Hey Ian, have you by chance had a moment to take a look here? We've tried a few things, including taking a rough stab at using a texture pool instead of a new Frame/FrameTexture for each frame, but that didn't seem to help.
https://github.com/claytercek/libglvideo/commit/fb3adeb99ce8541142daea8dbb646b40d8edfc18

Here are some screenshots from different memory snapshots in VS (stacks view & types view). Not a ton of insight here, but one thing that's curious is in the stacks view (first image) is shows a size diff of +2MB, but in the types view, there is only a ~150KB increase in mem shown. Where did the rest of it go??

![stacks-view](https://user-images.githubusercontent.com/2334552/60125469-db619600-9759-11e9-8c4f-3f8d1c3c6332.png)

![types-view](https://user-images.githubusercontent.com/2334552/60125468-db619600-9759-11e9-8352-677ac9e245e0.png)

Any ideas on additional things to try or look into?

**Comment by heisters** [comment] 2019-06-25 20:28
Sorry, I haven't had a chance to look at it yet. I've blocked out some time later this week.

**Comment by heisters** [comment] 2019-06-28 22:36
I don't think  33a7b36 should fix the leak, but please see if it changes anything for you.

It may have something to do with std::deque (the underlying type for concurrent_queue) [not releasing memory until program exit.](https://stackoverflow.com/questions/5834754/stddeque-does-not-release-memory-until-program-exits) I wonder if this may even cause the shared_ptr (`Frame::ref`) to stick around? I'd think the memory leak would be a lot worse if that were the case. In any case, one option may be to rewrite concurrent_queue to use a custom buffer data type or maybe std::array.

**Comment by claytercek** [comment] 2019-07-01 19:38
@heisters thanks for looking into this! I did some digging around and found that the glFenceSync function in [Frame.cpp](https://github.com/heisters/libglvideo/blob/21f622baf2760a045b8b1b1a5d4644fa5d0c4812/src/Frame.cpp#L42) seems to be what's eating up our memory. I came up with a quick fix for this by calling glDeleteSync [in the Frame destructor](https://github.com/claytercek/libglvideo/commit/1a03664dc13489258d733c00a7b00081ea61fdd6#diff-76f89b751d681404c52704a8e267f8f0). Right now this seems to be working very well! No longer seeing any signs of a memory leak.

As far as I can tell this fix doesn't seem to have any adverse side effects, but also I am not 100% sure what role m_sync plays. Curious to hear your thoughts on this. Thanks!

**Comment by heisters** [comment] 2019-07-01 21:14
Good catch! Forgot `GLSync` is actually a typedef of `__GLSync *` and needs to be cleaned up manually.

The fence sync is to asynchronously check whether the PBO is finished buffering to the GPU. So this caught another potential bug where Movie would update the current texture before the texture was done buffering. In practice, this shouldn't happen unless your buffer sizes are set small, and/or GPU bandwidth is saturated. Nevertheless, I added a check to catch those cases, and make that fence sync actually useful.

Fixes are on master b60cc26b

**Closed as completed by heisters** 2019-07-01 21:14 UTC

**Comment by heisters** [comment] 2019-07-01 21:17
One other note, about @claytercek's texture pool patch. That's a good improvement, and something I've had in mind to do. If you can test and make sure it works well, I'd be happy to take a PR.
